SELECT
DISTINCT
'XY' ctt_analysis_entity, --'{dummy_analysis_entity}'
'50' ctt_delivering_entity, --'{dummy_delivering_entity}'
'XY1001' ctt_funding_entity, --'{dummy_analysis_entity}1001'
ctt_reporting_date,
concat('a',substring(md5(ctt_cms_contract_number),3,8),'xy',substring(md5(ctt_cms_contract_number),4,9),'z') ctt_cms_contract_number,
'SYS' ctt_source_system, --'{source_system}'
ctt_bevis_id,
ctt_status,
ctt_start_date,
ctt_end_date,
'EUR' ctt_contract_currency, --'{dummy_currency}'
ctt_trade_date,
ctt_acquisition_date,
ctt_nbv_local_cms,
ctt_restructuring_flag,
ctt_sales_price,
ctt_down_payment,
ctt_balloon_rv,
ctt_additional_financed_amount,
ctt_commission,
ctt_fee,
ctt_idc,
ctt_subsidy,
ctt_subsidy_percent,
ctt_security_deposit,
ctt_deposit_rate,
ctt_period_in_month,
ctt_fix_variable,
ctt_variable_type,
ctt_payment_mode,
ctt_cmsir,
ctt_day_conv,
ctt_fixing_period,
ctt_last_fixing,
ctt_next_fixing,
ctt_installment,
ctt_installment_count,
ctt_delinquent_amount,
'EUR' ctt_delinquent_amount_ccy, --'{dummy_currency}'
ctt_delinquent_days_contract,
ctt_cal_delinquency_bucket_name,
ctt_pd,
ctt_lgd,
ctt_triggering_event_flag,
ctt_continuation_deal,
ctt_date_of_last_restructuring,
ctt_number_restructurings,
ctt_opex,
ctt_nib_ratio,
ctt_co_r_v_r,
ctt_reserves_segment_contract,
ctt_economic_capital_ratio,
ctt_portfolio_cr,
ctt_portfolio_pp,
ctt_portfolio,
ctt_written_off_flag,
ctt_additional_collateral_type,
ctt_additional_collateral_amount,
ctt_insurance_ancillary,
ctt_insurance_gap,
ctt_insurance_motor,
ctt_insurance_ppi,
ctt_insurance_warranty,
ctt_tax_rate,
ctt_financial_product_group,
ctt_rv_guarantee_flag,
ctt_product_sap,
ctt_abs_code,
ctt_asset_type_segment,
ctt_brand,
ctt_new_used,
ctt_units,
ctt_model_sap,
ctt_additional_asset_information,
ctt_asset_model_date,
ctt_list_price,
concat('a',substring(md5(ctt_vin),3,8),'xy',substring(md5(ctt_vin),4,9),'z') ctt_vin,
ctt_vin_type,
ctt_borrower_type,
ctt_borrower_sub_type,
concat('a',substring(md5(ctt_customer_number),3,8),'xy',substring(md5(ctt_customer_number),4,9),'z') ctt_customer_number,
concat('a',substring(md5(ctt_customer_group_number),3,8),'xy',substring(md5(ctt_customer_group_number),4,9),'z') ctt_customer_group_number,
'XY' ctt_borrower_country, --'{dummy_analysis_entity}'
ctt_industry_segmentation,
ctt_rating,
ctt_rating_name,
ctt_rating_version,
ctt_scoring,
ctt_r_model_score_card,
ctt_r_model_score_card_version,
concat('a',substring(md5(ctt_dealer),3,8),'xy',substring(md5(ctt_dealer),4,9),'z') ctt_dealer,
ctt_branch,
ctt_campaign,
ctt_fda_1,
ctt_fda_2,
ctt_hostile_termination_flag,
ctt_loan_commitment_flag,
ctt_ifrs9_classification,
ctt_credit_impaired,
ctt_loan_limit,
ctt_impaired_information,
ctt_business_division,
ctt_business_line,
ctt_rating_scoring_flag,
ctt_portfolio_tm1,
ctt_icrsa_flag,
ctt_delinquency_reason_code,
ctt_ifrs9_country_region,
ctt_cal_baumuster,
ctt_cal_engine_style_text,
ctt_cal_product_txt,
ctt_cal_class_txt,
ctt_cal_typclass_text,
ctt_cal_product_comment,
ctt_cal_product_bmst,
ctt_cal_taxonomy_aligned,
ctt_drv_portfolio_type_tm1,
ctt_drv_portfolio_type_rdr,
'XYORGF' ctt_drv_portfolio_name_tm1, --'{dummy_analysis_entity}ORGF'
'XYORGF' ctt_drv_portfolio_name_rdr, --'{dummy_analysis_entity}ORGF'
ctt_cal_acquisition_period,
ctt_cal_max_cashflow_date,
ctt_cal_contract_status_name,
ctt_cal_financed_amount,
ctt_cal_upfront_payments,
ctt_cal_curr_rating_scoring_value,
ctt_cal_curr_rating_scoring_scaled,
ctt_cal_net_pay_out_amount,
ctt_cal_interest_type,
ctt_cal_contract_trade_date,
ctt_cal_curr_rating_scoring_id,
ctt_cal_delinquent_amount,
ctt_cal_cms_gross_exposure,
ctt_cal_contract_age,
ctt_cal_vehicle_age,
ctt_cal_technical_amortization,
ctt_cal_contract_term,
ctt_cal_amg_maybach_classification,
ctt_cal_luxury_segment,
ctt_cal_ifrs9_relevant,
ctt_cal_initial_rating_scoring_scaled,
ctt_cal_residual_term_in_months,
ctt_cal_contract_term_bucket,
ctt_cal_initial_rating_scoring_value,
ctt_cal_initial_rating_scoring_id,
ctt_cal_initial_rating_scoring_class,
ctt_cal_contract_last_fixing,
ctt_cal_contract_next_fixing,
ctt_cal_product_group_alm,
ctt_cal_curr_rating_scoring_class,
ctt_cal_downpayment_ratio,
ctt_cal_gross_exposure,
'XY10' ctt_balance_sheet_entity, --'{dummy_analysis_entity}10'
ctt_cal_nbv,
ctt_cal_effective_payment_frequency,
ctt_cal_nominal_deal_irr,
ctt_cal_effective_deal_irr,
ctt_cal_nominal_upfront_margin,
ctt_cal_upfront_margin_sensitivity,
ctt_cal_delinquent_days_contract,
ctt_cal_delinquent_days,
ctt_cal_default_indicator,
ctt_cal_date_of_default,
ctt_cal_time_since_default,
ctt_cal_default_status,
ctt_cal_impairment_indicator,
concat(concat('a',substring(md5(ctt_customer_number),3,8),'xy',substring(md5(ctt_customer_number),4,9),'z'),'::CMS_XY1000') ctt_position_id,
ctt_cal_product_group_reporting,
MGT_InsertTime,
MGT_UpdateTime,
MGT_ValidationStatus
FROM
westeurope_spire_platform_int.application_rdr_standard.std_us58_pd_contract --{table_name}
LIMIT 10; --{limit_number}